/********************************************************************
 * Module       : port                                              *
 * File Name    : port_PBcfg.c                                      *
 * Description  : Post build configuration for port driver          *
 * Author       : Mohamed Ashraf                                    *
 *******************************************************************/

#include "port.h"



PORT_ConfigType configurations = {
    {0 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{1 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{2 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{3 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{4 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{5 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{6 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{7 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{8 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{9 , PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{10, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{11, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{12, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{13, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{14, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{15, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{16, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{17, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{18, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{19, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{20, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{21, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{22, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{23, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{24, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{25, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{26, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{27, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{28, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{29, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{30, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{31, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{32, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{33, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
   ,{34, PORT_PIN_INPUT, PORT_PIN_FLOATING, PORT_INPUT_MODE, PORT_INPUT_FLOATING_CFG, PORT_PIN_LOW}
};